app = "youth-missionary-game"

[build]
  builder = "heroku/buildpacks:20"

[env]
  STREAMLIT_SERVER_PORT = "8080"
  STREAMLIT_SERVER_ADDRESS = "0.0.0.0"
  POSTGRES-CONNECTION-STRING = "" # Set this in production for Postgres

[deploy]
  release_command = "streamlit run src/Dashboard.py"